# Generated by Django 3.2 on 2022-03-05 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_module_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='module',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.module'),
            preserve_default=False,
        ),
    ]
